
title: Azen`s Blog
email: azen.cell@foxmail.com
github_username: AzenXu
#Building setting
markdown: kramdown

gems:
 - jekyll-feed
 - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

# Pagination
paginate: 5
paginate_path: "page:num"

#Serve setting
port: 3888
